spring:
 datasource:
  url: jdbc:mysql://120.48.8.184:3306/netbar_db?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
  username: connecter
  password: 123456
 thymeleaf:
  cache: false
 redis:
  host: 120.48.8.184
  port: 6379
  jedis:
   pool:
    max-idle: 8
    max-active: 8
    max-wait: 1000
    min-idle: 0

server:
 port: 8005